# Generated by Django 3.1.1 on 2020-11-04 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thanos',
        ),
        migrations.AddField(
            model_name='couple',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='couple',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couple',
            name='name',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='couple',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='core/images'),
        ),
    ]
