# Generated by Django 3.1.1 on 2020-11-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201105_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='couple',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
