# Generated by Django 3.1.1 on 2020-11-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201109_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='snapped',
            field=models.IntegerField(default=0),
        ),
    ]
